webtalk_init -webtalk_dir C:\\Users\\ASUS\\Desktop\\project_ps_only\\project_ps_only.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-03-16 18:34:35" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dh42oo0dp3vgccn51de4nloobq" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.484 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1521223235333" -context "sdk\\\\hardware/1521223235333"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1521223235333"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1521223235333"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1521223235333"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.4.1" -context "sdk\\\\hardware/1521223235333"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1521223235333"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1521223235333"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1521223235333"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1521223235333"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1521223235333"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1521223235333"
webtalk_add_data -client sdk -key uid -value "1521223256251" -context "sdk\\\\bsp/1521223256251"
webtalk_add_data -client sdk -key hwid -value "1521223235333" -context "sdk\\\\bsp/1521223256251"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1521223256251"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1521223256251"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1521223256251"
webtalk_add_data -client sdk -key uid -value "1521223342646" -context "sdk\\\\application/1521223342646"
webtalk_add_data -client sdk -key hwid -value "1521223235333" -context "sdk\\\\application/1521223342646"
webtalk_add_data -client sdk -key bspid -value "1521223256251" -context "sdk\\\\application/1521223342646"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1521223342646"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1521223342646"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1521223342646"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1521223342646"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1521223342646"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1521223342646"
webtalk_add_data -client sdk -key projSize -value "217.375" -context "sdk\\\\application/1521223342646"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1521225275501"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1521225275501"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1521225275501"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1521225275501"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1521225275501"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1521225275501"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1521225275501"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1521225275501"
webtalk_transmit -clientid 2686388959 -regid "" -xml C:\\Users\\ASUS\\Desktop\\project_ps_only\\project_ps_only.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\ASUS\\Desktop\\project_ps_only\\project_ps_only.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\ASUS\\Desktop\\project_ps_only\\project_ps_only.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
